name: Build and Release

on:
  release:
    types: [created]

# 添加顶级权限配置
permissions:
  contents: write      # 允许上传到 release
  packages: write     # 允许发布包
  actions: write      # 允许管理 actions

jobs:
  build:
    name: Build ConnectDev
    runs-on: ${{ matrix.os }}
    # 也可以只在 build job 中添加权限
    permissions:
      contents: write  # 这是上传 release assets 所需的权限
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: connectdev-linux
          - os: windows-latest
            asset_name: connectdev-windows.exe
          - os: macos-latest
            asset_name: connectdev-macos
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build twine pyinstaller

    - name: Run Tests
      run: pytest test/

    - name: Build Executable
      run: pyinstaller connectdev.spec

    - name: Generate checksum
      run: |
        cd dist
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          certutil -hashfile connectdev.exe SHA256 > connectdev-${{ matrix.asset_name }}.sha256
        else
          shasum -a 256 connectdev > connectdev-${{ matrix.asset_name }}.sha256
        fi

    - name: Package
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          7z a connectdev-${{ matrix.asset_name }}.zip ./dist/connectdev.exe
        else
          tar -czf connectdev-${{ matrix.asset_name }}.tar.gz -C dist connectdev
        fi

    - name: Upload Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./connectdev-${{ matrix.asset_name }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
        asset_name: connectdev-${{ matrix.asset_name }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
        asset_content_type: ${{ matrix.os == 'windows-latest' && 'application/zip' || 'application/gzip' }}

    - name: Upload Checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/connectdev-${{ matrix.asset_name }}.sha256
        asset_name: connectdev-${{ matrix.asset_name }}.sha256
        asset_content_type: text/plain

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
